// import monacoThemes from "monaco-themes/themes/themelist.json";
// import fs
const fs = require('fs');
async function genThemes() {
    console.log('>>>> Generating pre-theme data for SSR')
    const monacoThemeModuleDir = 'node_modules/monaco-themes/themes';
    const themeListPath = `${monacoThemeModuleDir}/themelist.json`;
    const thmemeListFile = fs.readFileSync(themeListPath, 'utf8');
    const themeJson = JSON.parse(thmemeListFile); // id:name
    const themeNames = Object.values(themeJson);

    const themes = [];
    for (const name of themeNames) {
        const themeJsonPath = `${monacoThemeModuleDir}/${name}.json`;
        const themeJsonFile = fs.readFileSync(themeJsonPath, 'utf8');
        const themeJson = JSON.parse(themeJsonFile);
        const theme = {
            background: themeJson.colors['editor.background'],
            forground: themeJson.colors['editor.foreground'],
            value: name,
            label: name
        }
        themes.push(theme);
    }

    const outputPath = 'src/data/themes.ts';
    const outputStr = `
    // This file is generated by pre-theme_gen.ts
    // Do not modify this file directly

    import { ThemeSelectorInterface } from "@/models/theme";
    export const themes: ThemeSelectorInterface[] = ${JSON.stringify(themes, null, 4)}
    `
    fs.writeFileSync(outputPath, outputStr);

    console.log('>>>> Done generating pre-theme data for SSR')
}

genThemes();