
    // This file is generated by pre-theme_gen.ts
    // Do not modify this file directly

    import { ThemeSelectorInterface } from "@/models/theme";
    export const themes: ThemeSelectorInterface[] = [
    {
        "background": "#FFFFFF",
        "forground": "#3B3B3B",
        "value": "active4d",
        "label": "Active4D"
    },
    {
        "background": "#000000",
        "forground": "#FFFFFF",
        "value": "all-hallows-eve",
        "label": "All Hallows Eve"
    },
    {
        "background": "#200020",
        "forground": "#D0D0FF",
        "value": "amy",
        "label": "Amy"
    },
    {
        "background": "#372725",
        "forground": "#E6E1C4",
        "value": "birds-of-paradise",
        "label": "Birds of Paradise"
    },
    {
        "background": "#0C1021",
        "forground": "#F8F8F8",
        "value": "blackboard",
        "label": "Blackboard"
    },
    {
        "background": "#0D0D0DFA",
        "forground": "#EEEEEE",
        "value": "brilliance-black",
        "label": "Brilliance Black"
    },
    {
        "background": "#050505FA",
        "forground": "#CDCDCD",
        "value": "brilliance-dull",
        "label": "Brilliance Dull"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "chrome-devtools",
        "label": "Chrome DevTools"
    },
    {
        "background": "#191919",
        "forground": "#929292",
        "value": "clouds-midnight",
        "label": "Clouds Midnight"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "clouds",
        "label": "Clouds"
    },
    {
        "background": "#002240",
        "forground": "#FFFFFF",
        "value": "cobalt",
        "label": "Cobalt"
    },
    {
        "background": "#193549",
        "forground": "#FFFFFF",
        "value": "cobalt2",
        "label": "Cobalt2"
    },
    {
        "background": "#F9F9F9",
        "forground": "#080808",
        "value": "dawn",
        "label": "Dawn"
    },
    {
        "background": "#282a36",
        "forground": "#f8f8f2",
        "value": "dracula",
        "label": "Dracula"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "dreamweaver",
        "label": "Dreamweaver"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "eiffel",
        "label": "Eiffel"
    },
    {
        "background": "#2A211C",
        "forground": "#BDAE9D",
        "value": "espresso-libre",
        "label": "Espresso Libre"
    },
    {
        "background": "#24292e",
        "forground": "#f6f8fa",
        "value": "github-dark",
        "label": "GitHub Dark"
    },
    {
        "background": "#ffffff",
        "forground": "#24292e",
        "value": "github-light",
        "label": "GitHub Light"
    },
    {
        "background": "#F8F8FF",
        "forground": "#000000",
        "value": "github",
        "label": "GitHub"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "idle",
        "label": "IDLE"
    },
    {
        "background": "#E8E9E8",
        "forground": "#363636",
        "value": "katzenmilch",
        "label": "Katzenmilch"
    },
    {
        "background": "#E8E9E8",
        "forground": "#363636",
        "value": "kuroir-theme",
        "label": "Kuroir Theme"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "lazy",
        "label": "LAZY"
    },
    {
        "background": "#969696",
        "forground": "#000000",
        "value": "magicwb--amiga-",
        "label": "MagicWB (Amiga)"
    },
    {
        "background": "#161616",
        "forground": "#E6E1DC",
        "value": "merbivore-soft",
        "label": "Merbivore Soft"
    },
    {
        "background": "#161616",
        "forground": "#E6E1DC",
        "value": "merbivore",
        "label": "Merbivore"
    },
    {
        "background": "#272822",
        "forground": "#F8F8F2",
        "value": "monokai-bright",
        "label": "Monokai Bright"
    },
    {
        "background": "#272822",
        "forground": "#F8F8F2",
        "value": "monokai",
        "label": "Monokai"
    },
    {
        "background": "#011627",
        "forground": "#d6deeb",
        "value": "night-owl",
        "label": "Night Owl"
    },
    {
        "background": "#2E3440",
        "forground": "#D8DEE9",
        "value": "nord",
        "label": "Nord"
    },
    {
        "background": "#1B2B34",
        "forground": "#CDD3DE",
        "value": "oceanic-next",
        "label": "Oceanic Next"
    },
    {
        "background": "#211E1E",
        "forground": "#DADADA",
        "value": "pastels-on-dark",
        "label": "Pastels on Dark"
    },
    {
        "background": "#F1F1F1",
        "forground": "#000000",
        "value": "slush-and-poppies",
        "label": "Slush and Poppies"
    },
    {
        "background": "#002B36",
        "forground": "#839496",
        "value": "solarized-dark",
        "label": "Solarized-dark"
    },
    {
        "background": "#FDF6E3",
        "forground": "#586E75",
        "value": "solarized-light",
        "label": "Solarized-light"
    },
    {
        "background": "#0D0D0D",
        "forground": "#DDE6CF",
        "value": "spacecadet",
        "label": "SpaceCadet"
    },
    {
        "background": "#000000",
        "forground": "#F8F8F8",
        "value": "sunburst",
        "label": "Sunburst"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "textmate--mac-classic-",
        "label": "Textmate (Mac Classic)"
    },
    {
        "background": "#002451",
        "forground": "#FFFFFF",
        "value": "tomorrow-night-blue",
        "label": "Tomorrow-Night-Blue"
    },
    {
        "background": "#000000",
        "forground": "#DEDEDE",
        "value": "tomorrow-night-bright",
        "label": "Tomorrow-Night-Bright"
    },
    {
        "background": "#2D2D2D",
        "forground": "#CCCCCC",
        "value": "tomorrow-night-eighties",
        "label": "Tomorrow-Night-Eighties"
    },
    {
        "background": "#1D1F21",
        "forground": "#C5C8C6",
        "value": "tomorrow-night",
        "label": "Tomorrow-Night"
    },
    {
        "background": "#FFFFFF",
        "forground": "#4D4D4C",
        "value": "tomorrow",
        "label": "Tomorrow"
    },
    {
        "background": "#141414",
        "forground": "#F8F8F8",
        "value": "twilight",
        "label": "Twilight"
    },
    {
        "background": "#000000F7",
        "forground": "#F8F8F8",
        "value": "upstream-sunburst",
        "label": "Upstream Sunburst"
    },
    {
        "background": "#000000",
        "forground": "#FFFFFF",
        "value": "vibrant-ink",
        "label": "Vibrant Ink"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "xcode-default",
        "label": "Xcode_default"
    },
    {
        "background": "#404040",
        "forground": "#DEDEDE",
        "value": "zenburnesque",
        "label": "Zenburnesque"
    },
    {
        "background": "#EEEEEEEB",
        "forground": "#000000",
        "value": "iplastic",
        "label": "iPlastic"
    },
    {
        "background": "#323232",
        "forground": "#FFFFFF",
        "value": "idlefingers",
        "label": "idleFingers"
    },
    {
        "background": "#0B0A09",
        "forground": "#FCFFE0",
        "value": "krtheme",
        "label": "krTheme"
    },
    {
        "background": "#222C28",
        "forground": "#FFFFFF",
        "value": "monoindustrial",
        "label": "monoindustrial"
    }
]
    