
    // This file is generated by pre-theme_gen.ts
    // Do not modify this file directly

    import { ThemeSelectorInterface } from "@/models/theme";
    export const themes: ThemeSelectorInterface[] = [
    {
        "background": "#FFFFFF",
        "forground": "#3B3B3B",
        "value": "Active4D",
        "label": "Active4D"
    },
    {
        "background": "#000000",
        "forground": "#FFFFFF",
        "value": "All Hallows Eve",
        "label": "All Hallows Eve"
    },
    {
        "background": "#200020",
        "forground": "#D0D0FF",
        "value": "Amy",
        "label": "Amy"
    },
    {
        "background": "#372725",
        "forground": "#E6E1C4",
        "value": "Birds of Paradise",
        "label": "Birds of Paradise"
    },
    {
        "background": "#0C1021",
        "forground": "#F8F8F8",
        "value": "Blackboard",
        "label": "Blackboard"
    },
    {
        "background": "#0D0D0DFA",
        "forground": "#EEEEEE",
        "value": "Brilliance Black",
        "label": "Brilliance Black"
    },
    {
        "background": "#050505FA",
        "forground": "#CDCDCD",
        "value": "Brilliance Dull",
        "label": "Brilliance Dull"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Chrome DevTools",
        "label": "Chrome DevTools"
    },
    {
        "background": "#191919",
        "forground": "#929292",
        "value": "Clouds Midnight",
        "label": "Clouds Midnight"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Clouds",
        "label": "Clouds"
    },
    {
        "background": "#002240",
        "forground": "#FFFFFF",
        "value": "Cobalt",
        "label": "Cobalt"
    },
    {
        "background": "#193549",
        "forground": "#FFFFFF",
        "value": "Cobalt2",
        "label": "Cobalt2"
    },
    {
        "background": "#F9F9F9",
        "forground": "#080808",
        "value": "Dawn",
        "label": "Dawn"
    },
    {
        "background": "#282a36",
        "forground": "#f8f8f2",
        "value": "Dracula",
        "label": "Dracula"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Dreamweaver",
        "label": "Dreamweaver"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Eiffel",
        "label": "Eiffel"
    },
    {
        "background": "#2A211C",
        "forground": "#BDAE9D",
        "value": "Espresso Libre",
        "label": "Espresso Libre"
    },
    {
        "background": "#24292e",
        "forground": "#f6f8fa",
        "value": "GitHub Dark",
        "label": "GitHub Dark"
    },
    {
        "background": "#ffffff",
        "forground": "#24292e",
        "value": "GitHub Light",
        "label": "GitHub Light"
    },
    {
        "background": "#F8F8FF",
        "forground": "#000000",
        "value": "GitHub",
        "label": "GitHub"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "IDLE",
        "label": "IDLE"
    },
    {
        "background": "#E8E9E8",
        "forground": "#363636",
        "value": "Katzenmilch",
        "label": "Katzenmilch"
    },
    {
        "background": "#E8E9E8",
        "forground": "#363636",
        "value": "Kuroir Theme",
        "label": "Kuroir Theme"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "LAZY",
        "label": "LAZY"
    },
    {
        "background": "#969696",
        "forground": "#000000",
        "value": "MagicWB (Amiga)",
        "label": "MagicWB (Amiga)"
    },
    {
        "background": "#161616",
        "forground": "#E6E1DC",
        "value": "Merbivore Soft",
        "label": "Merbivore Soft"
    },
    {
        "background": "#161616",
        "forground": "#E6E1DC",
        "value": "Merbivore",
        "label": "Merbivore"
    },
    {
        "background": "#272822",
        "forground": "#F8F8F2",
        "value": "Monokai Bright",
        "label": "Monokai Bright"
    },
    {
        "background": "#272822",
        "forground": "#F8F8F2",
        "value": "Monokai",
        "label": "Monokai"
    },
    {
        "background": "#011627",
        "forground": "#d6deeb",
        "value": "Night Owl",
        "label": "Night Owl"
    },
    {
        "background": "#2E3440",
        "forground": "#D8DEE9",
        "value": "Nord",
        "label": "Nord"
    },
    {
        "background": "#1B2B34",
        "forground": "#CDD3DE",
        "value": "Oceanic Next",
        "label": "Oceanic Next"
    },
    {
        "background": "#211E1E",
        "forground": "#DADADA",
        "value": "Pastels on Dark",
        "label": "Pastels on Dark"
    },
    {
        "background": "#F1F1F1",
        "forground": "#000000",
        "value": "Slush and Poppies",
        "label": "Slush and Poppies"
    },
    {
        "background": "#002B36",
        "forground": "#839496",
        "value": "Solarized-dark",
        "label": "Solarized-dark"
    },
    {
        "background": "#FDF6E3",
        "forground": "#586E75",
        "value": "Solarized-light",
        "label": "Solarized-light"
    },
    {
        "background": "#0D0D0D",
        "forground": "#DDE6CF",
        "value": "SpaceCadet",
        "label": "SpaceCadet"
    },
    {
        "background": "#000000",
        "forground": "#F8F8F8",
        "value": "Sunburst",
        "label": "Sunburst"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Textmate (Mac Classic)",
        "label": "Textmate (Mac Classic)"
    },
    {
        "background": "#002451",
        "forground": "#FFFFFF",
        "value": "Tomorrow-Night-Blue",
        "label": "Tomorrow-Night-Blue"
    },
    {
        "background": "#000000",
        "forground": "#DEDEDE",
        "value": "Tomorrow-Night-Bright",
        "label": "Tomorrow-Night-Bright"
    },
    {
        "background": "#2D2D2D",
        "forground": "#CCCCCC",
        "value": "Tomorrow-Night-Eighties",
        "label": "Tomorrow-Night-Eighties"
    },
    {
        "background": "#1D1F21",
        "forground": "#C5C8C6",
        "value": "Tomorrow-Night",
        "label": "Tomorrow-Night"
    },
    {
        "background": "#FFFFFF",
        "forground": "#4D4D4C",
        "value": "Tomorrow",
        "label": "Tomorrow"
    },
    {
        "background": "#141414",
        "forground": "#F8F8F8",
        "value": "Twilight",
        "label": "Twilight"
    },
    {
        "background": "#000000F7",
        "forground": "#F8F8F8",
        "value": "Upstream Sunburst",
        "label": "Upstream Sunburst"
    },
    {
        "background": "#000000",
        "forground": "#FFFFFF",
        "value": "Vibrant Ink",
        "label": "Vibrant Ink"
    },
    {
        "background": "#FFFFFF",
        "forground": "#000000",
        "value": "Xcode_default",
        "label": "Xcode_default"
    },
    {
        "background": "#404040",
        "forground": "#DEDEDE",
        "value": "Zenburnesque",
        "label": "Zenburnesque"
    },
    {
        "background": "#EEEEEEEB",
        "forground": "#000000",
        "value": "iPlastic",
        "label": "iPlastic"
    },
    {
        "background": "#323232",
        "forground": "#FFFFFF",
        "value": "idleFingers",
        "label": "idleFingers"
    },
    {
        "background": "#0B0A09",
        "forground": "#FCFFE0",
        "value": "krTheme",
        "label": "krTheme"
    },
    {
        "background": "#222C28",
        "forground": "#FFFFFF",
        "value": "monoindustrial",
        "label": "monoindustrial"
    }
]
    